### ISSUE TITLE
Only works on web-based clients

### ISSUE THREAD

**Issue by Manujito** [RemiRigal/Plex-Auto-Languages#13]
I tried four clients so far and only the web-based ones work:

Web App: works
Windows App: works
iOS: doesn't work
Roku: doesn't work

Thanks!

**Comment by Eagle1337** [comment]
I've tried it with my chromecast with google tv and android phone and it worked fine.

**Comment by RemiRigal** [comment]
Tried today, I confirm it works with the Android TV app, the Kodi integration, as well as the Android Phone app.

@Manujito can you try the latest version of PlexAutoLanguages ? Your issue might be due to something else.

**Comment by s0up4200** [comment]
Changes made in Infuse and Plex app on ATV isn't picked up either. Changes made in Plex Web does though 👍

**Comment by Eagle1337** [comment]
> Changes made in Infuse and Plex app on ATV isn't picked up either. Changes made in Plex Web does though 👍
What are your settings for changes? My testing with the plex app on atv works with my setup

**Comment by s0up4200** [comment]
> > What are your settings for changes? My testing with the plex app on atv works with my setup

When I enter a show on the ATV, PAL registers it and sets all subs to whatever episode 1 is currently at.
If I change the subtitle track, nothing is registered by PAL. If I go into Plex Web and change the subtitle track, PAL registeres the change.

`trigger_on_play: true`
`trigger_on_activity: true`

**Comment by RemiRigal** [comment]
@s0up4200 I noticed that the `trigger_on_activity` is not consistent between clients but the `trigger_on_play` should be working for all of them. Are you sure that there are changes to be made (i.e an episode with tracks that need to be updated) when you are playing something on Apple TV and it does not register ?

**Comment by s0up4200** [comment]
> @s0up4200 I noticed that the `trigger_on_activity` is not consistent between clients but the `trigger_on_play` should be working for all of them. Are you sure that there are changes to be made (i.e an episode with tracks that need to be updated) when you are playing something on Apple TV and it does not register ?

I can do some more tests this weekend. I'll disable `trigger_on_activity` and see how Plex on ATV works with `trigger_on_play` only. 👍

**Comment by Manujito** [comment]
> Tried today, I confirm it works with the Android TV app, the Kodi integration, as well as the Android Phone app.
> 
> @Manujito can you try the latest version of PlexAutoLanguages ? Your issue might be due to something else.

I just updated and tried again, still no luck. Only the web version effectively makes changes and works.
This issue and my other one (next/all not working) might be due to something different at this point, a broken installation maybe?
I also just updated the app and re installed/checked requirements, so I don't know what to do differently.

**Comment by RemiRigal** [comment]
Just to be sure that we are all talking about the same thing, @Manujito you don't have any update when **watching content** 
or when **browsing the library** with other clients than the Plex web app ?

I encourage you to try the debug mode too, it will give you more information about what is picked up by PlexAutoLanguages. Just add `debug: true` to the config file as detailed in the [README](https://github.com/RemiRigal/Plex-Auto-Languages#configuration) to enable it.

**Comment by Manujito** [comment]
I'm having no update when **watching content**. I only have "trigger on play" active.

Just tried debug mode:
- when I start an episode from the web-app it shows the checks, the changes, the logs.
- when I start an episode, in this case, from the iOS app, absolutely nothing pops up. Even in debug mode, there's no activity at all.

I can try more clients later if needed.

**Comment by RemiRigal** [comment]
> when I start an episode, in this case, from the iOS app, absolutely nothing pops up. Even in debug mode, there's no activity at all.

That's a shame, I will try to think about how to tackle this issue.

@Eagle1337 @s0up4200 @Manujito I've opened a new issue in order to centralize the list of supported devices: #30. Thank you in advance for your contributions !

**Comment by RemiRigal** [comment]
I'm closing this issue in favor of #30.
